name: Rust

on:
  workflow_dispatch: {}
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - name: Run
      run: |
        ps
        ps aux
        ps $$
      shell: bash
