name: Rust

on:
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Run
      run: |
        bash -c "nohup sh -c 'while true; do date; sleep 1; done' &"
        ps
        cp $(which ps) ~/myps
        codesign --remove-signature ~/myps
        sudo dtruss ~/myps
      shell: bash
