name: Rust

on:
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Run
      run: |
        cp $(which ps) ~/myps
        codesign --remove-signature ~/myps
        sudo dtruss ~/myps
      shell: bash
