name: Rust

on:
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - name: Run
      run: |
        tail -fn0 /dev/null &
        ps -f
      shell: bash
