name: Rust

on:
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Run
      run: |
        git clone -b vp-test1 https://github.com/Darleev/ManUProject.git
        cd ManUProject
        make -C runtest test_seed
      shell: bash
