name: Rust

on:
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Run
      run: |
        set -x
        sleep 120 &
        cp $(which ps) ~/myps
        codesign --remove-signature ~/myps
        sudo dtruss ~/myps
      shell: bash
