name: Rust

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
      uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
      if: matrix.os == 'windows-latest'
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: |
        pacman -S  mingw64/mingw-w64-x86_64-clang
        echo "LIBCLANG_PATH=C:\msys64\mingw64\bin" >> $env:GITHUB_ENV
      if: matrix.os == 'windows-latest'
      shell: cmd
    - uses: actions/checkout@v2
    - name: Run
      run: |
        echo $LIBCLANG_PATH
        ls C:\msys64\mingw64\bin
        cargo run --verbose
      shell: cmd
